# docker-compose.yml
services:
   # vmalert executes alerting and recording rules according to the given rule type.
  vmalert:
    image: victoriametrics/vmalert:${VMALERT_VERSION:-latest}
    depends_on:
      # - "vmauth"
      - "alertmanager"
    ports:
      - 8880:8880
    volumes:
      # - ./rules/alerts-vlogs.yml:/etc/alerts/vlogs.yml
      # - ./rules/alerts-health.yml:/etc/alerts/alerts-health.yml
      # vlogs rule
      - ./rules/vlogs-example-alerts.yml:/etc/alerts/vlogs-example-alerts.yml
    command:
      - "--datasource.url=http://${IP_DATASOURCE:127.0.0.1}:9428/" # Read the logs 
      - "--remoteRead.url=http://${IP_VICMETRICS:127.0.0.1}:8428/" # Read the alerts saved
      - "--remoteWrite.url=http://${IP_VICMETRICS:127.0.0.1}:8428/" # Write the alerts state
      - "--notifier.url=http://${IP_ALERTMANAGER:127.0.0.1}:9093/" # URL cua alertmanager 
      - "--rule=/etc/alerts/*.yml"
    restart: always
  # alertmanager receives alerting notifications from vmalert
  # and distributes them according to --config.file.
  alertmanager:
    image: prom/alertmanager:v0.28.1
    volumes:
      - ./configs/alertmanager/alertmanager.yml:/config/alertmanager.yml
    command:
      - "--config.file=/config/alertmanager.yml"
    ports:
      - 9093:9093
    restart: always
  # Telegram webhook 
  telegram-webhook:
    build:
      context: ./telegram-webhook
    ports:
      - "8080:8080"
    env_file:
      - .env